scripts: update default classpath
Use standard classpath for plugins, but support special COAT classpath
for CLAS12.

diff --git a/scripts/unix/clara-shell b/scripts/unix/clara-shell
--- a/scripts/unix/clara-shell
+++ b/scripts/unix/clara-shell
@@ -5,33 +5,32 @@ if [ -z "${CLARA_HOME}" ]; then
     exit 1
 fi
 
-if [ -z "${CLASSPATH}" ]; then
-    # Find plugins directory
-    CLASSPATH="${CLARA_HOME}/lib/*"
-    if [ -n "${CLARA_PLUGINS}" ]; then
-        if [ ! -d "${CLARA_PLUGINS}" ]; then
-            echo "Error: \$CLARA_PLUGINS is not a directory."
-            exit 1
-        fi
-        plugins_dir="${CLARA_PLUGINS}"
-     # Add every plugin
-      for plugin in "${plugins_dir}"/*; do
-        if [ -d "${plugin}" ]; then
-            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
-
-            # Support subdirectories inside lib/
-            for libdir in "${plugin}"/lib/*; do
-                if [ -d "${libdir}" ]; then
-                    CLASSPATH+=":${libdir}/*"
-                fi
-            done
-        fi
-      done
-    else
-      # Default is clas12 plugin
-        plugins_dir="${CLARA_HOME}/plugins/clas12"
-        CLASSPATH+=":${plugins_dir}/lib/clas/*:${plugins_dir}/lib/services/*"
+# find plugins directory
+if [ -n "${CLARA_PLUGINS}" ]; then
+    if [ ! -d "${CLARA_PLUGINS}" ]; then
+        echo "Error: \$CLARA_PLUGINS is not a directory."
+        exit 1
     fi
+    plugins_dir="${CLARA_PLUGINS}"
+else
+    plugins_dir="${CLARA_HOME}/plugins"
+fi
+
+# set default classpath
+if [ -z "${CLASSPATH}" ]; then
+    CLASSPATH="${CLARA_HOME}/lib/*"
+
+    # Add every plugin
+    for plugin in "${plugins_dir}"/*/; do
+        plugin=${plugin%*/}
+        if [ "${plugin##*/}" = "clas12" ]; then # COAT has special needs
+            CLASSPATH+=":${plugin}/lib/clas/*:${plugin}/lib/services/*"
+        else
+            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
+        fi
+    done
+
+    CLASSPATH+=":${CLARA_HOME}/services/*"
     export CLASSPATH
 fi
 
