temporary for class to test....

diff --git a/scripts/unix/clara-shell b/scripts/unix/clara-shell
--- a/scripts/unix/clara-shell
+++ b/scripts/unix/clara-shell
@@ -5,36 +5,38 @@ if [ -z "${CLARA_HOME}" ]; then
     exit 1
 fi
 
-if [ -z "${CLASSPATH}" ]; then
-    # Find plugins directory
-    CLASSPATH="${CLARA_HOME}/lib/*"
-    if [ -n "${CLARA_PLUGINS}" ]; then
-        if [ ! -d "${CLARA_PLUGINS}" ]; then
-            echo "Error: \$CLARA_PLUGINS is not a directory."
-            exit 1
-        fi
-        plugins_dir="${CLARA_PLUGINS}"
-    else
-        plugins_dir="${CLARA_HOME}/plugins/clas12"
-    fi
+export CLASSPATH="$CLARA_HOME/lib/*:$CLARA_HOME/plugins/clas12/lib/clas/*:$CLARA_HOME/plugins/clas12/lib/services/*"
 
-    # Add every plugin
-    for plugin in "${plugins_dir}"/*; do
-        if [ -d "${plugin}" ]; then
-            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
-
-            # Support subdirectories inside lib/
-            for libdir in "${plugin}"/lib/*; do
-                if [ -d "${libdir}" ]; then
-                    CLASSPATH+=":${libdir}/*"
-                fi
-            done
-        fi
-    done
-
-    CLASSPATH+=":${CLARA_HOME}/services/*"
-    export CLASSPATH
-fi
+#if [ -z "${CLASSPATH}" ]; then
+#    # Find plugins directory
+#    CLASSPATH="${CLARA_HOME}/lib/*"
+#    if [ -n "${CLARA_PLUGINS}" ]; then
+#        if [ ! -d "${CLARA_PLUGINS}" ]; then
+#            echo "Error: \$CLARA_PLUGINS is not a directory."
+#            exit 1
+#        fi
+#        plugins_dir="${CLARA_PLUGINS}"
+#    else
+#        plugins_dir="${CLARA_HOME}/plugins"
+#    fi
+#
+#    # Add every plugin
+#    for plugin in "${plugins_dir}"/*; do
+#        if [ -d "${plugin}" ]; then
+#            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
+#
+#            # Support subdirectories inside lib/
+#            for libdir in "${plugin}"/lib/*; do
+#                if [ -d "${libdir}" ]; then
+#                    CLASSPATH+=":${libdir}/*"
+#                fi
+#            done
+#        fi
+#    done
+#
+#    CLASSPATH+=":${CLARA_HOME}/services/*"
+#    export CLASSPATH
+#fi
 
 if [ -n "${JAVA_OPTS}" ]; then
     jvm_options=(${JAVA_OPTS})
