if CLARA_PLUGIN env variable is not set, it assumes clas12 plugin by default.

diff --git a/scripts/unix/j_dpe b/scripts/unix/j_dpe
--- a/scripts/unix/j_dpe
+++ b/scripts/unix/j_dpe
@@ -6,22 +6,17 @@ if [ -z "${CLARA_HOME}" ]; then
     exit 1
 fi
 
-# Find plugins directory
-if [ -n "${CLARA_PLUGINS}" ]; then
-    if [ ! -d "${CLARA_PLUGINS}" ]; then
-        echo "Error: \$CLARA_PLUGINS is not a directory."
-        exit 1
-    fi
-    plugins_dir="${CLARA_PLUGINS}"
-else
-    plugins_dir="${CLARA_HOME}/plugins"
-fi
-
 if [ -z "${CLASSPATH}" ]; then
+    # Find plugins directory
     CLASSPATH="${CLARA_HOME}/lib/*"
-
-    # Add every plugin
-    for plugin in "${plugins_dir}"/*; do
+    if [ -n "${CLARA_PLUGINS}" ]; then
+        if [ ! -d "${CLARA_PLUGINS}" ]; then
+            echo "Error: \$CLARA_PLUGINS is not a directory."
+            exit 1
+        fi
+        plugins_dir="${CLARA_PLUGINS}"
+     # Add every plugin
+      for plugin in "${plugins_dir}"/*; do
         if [ -d "${plugin}" ]; then
             CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
 
@@ -32,7 +27,39 @@ if [ -z "${CLASSPATH}" ]; then
                 fi
             done
         fi
-    done
+      done
+    else
+        plugins_dir="${CLARA_HOME}/plugins/clas12"
+           CLASSPATH+=":${plugins_dir}/lib/services/*:${plugin_dir}/lib/clas/*"
+    fi
+
+## Find plugins directory
+#if [ -n "${CLARA_PLUGINS}" ]; then
+#    if [ ! -d "${CLARA_PLUGINS}" ]; then
+#        echo "Error: \$CLARA_PLUGINS is not a directory."
+#        exit 1
+#    fi
+#    plugins_dir="${CLARA_PLUGINS}"
+#else
+#    plugins_dir="${CLARA_HOME}/plugins"
+#fi
+#
+#if [ -z "${CLASSPATH}" ]; then
+#    CLASSPATH="${CLARA_HOME}/lib/*"
+#
+#    # Add every plugin
+#    for plugin in "${plugins_dir}"/*; do
+#        if [ -d "${plugin}" ]; then
+#            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
+#
+#            # Support subdirectories inside lib/
+#            for libdir in "${plugin}"/lib/*; do
+#                if [ -d "${libdir}" ]; then
+#                    CLASSPATH+=":${libdir}/*"
+#                fi
+#            done
+#        fi
+#    done
 
     CLASSPATH+=":${CLARA_HOME}/services/*"
     export CLASSPATH
