Default class path for clas12 plugin.

diff --git a/scripts/unix/j_dpe b/scripts/unix/j_dpe
--- a/scripts/unix/j_dpe
+++ b/scripts/unix/j_dpe
@@ -5,66 +5,35 @@ if [ -z "${CLARA_HOME}" ]; then
     echo "Error: \$CLARA_HOME is not defined."
     exit 1
 fi
-export CLASSPATH="$CLARA_HOME/lib/*:$CLARA_HOME/plugins/clas12/lib/clas/*:$CLARA_HOME/plugins/clas12/lib/services/*"
+if [ -z "${CLASSPATH}" ]; then
+    # Find plugins directory
+    CLASSPATH="${CLARA_HOME}/lib/*"
+    if [ -n "${CLARA_PLUGINS}" ]; then
+        if [ ! -d "${CLARA_PLUGINS}" ]; then
+            echo "Error: \$CLARA_PLUGINS is not a directory."
+            exit 1
+        fi
+        plugins_dir="${CLARA_PLUGINS}"
+     # Add every plugin
+      for plugin in "${plugins_dir}"/*; do
+        if [ -d "${plugin}" ]; then
+            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
 
-#if [ -z "${CLASSPATH}" ]; then
-#    # Find plugins directory
-#    CLASSPATH="${CLARA_HOME}/lib/*"
-#    if [ -n "${CLARA_PLUGINS}" ]; then
-#        if [ ! -d "${CLARA_PLUGINS}" ]; then
-#            echo "Error: \$CLARA_PLUGINS is not a directory."
-#            exit 1
-#        fi
-#        plugins_dir="${CLARA_PLUGINS}"
-#     # Add every plugin
-#      for plugin in "${plugins_dir}"/*; do
-#        if [ -d "${plugin}" ]; then
-#            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
-#
-#            # Support subdirectories inside lib/
-#            for libdir in "${plugin}"/lib/*; do
-#                if [ -d "${libdir}" ]; then
-#                    CLASSPATH+=":${libdir}/*"
-#                fi
-#            done
-#        fi
-#      done
-#    else
-#        plugins_dir="${CLARA_HOME}/plugins/clas12"
-#           CLASSPATH+=":${plugins_dir}/lib/services/*:${plugin_dir}/lib/clas/*"
-#    fi
-
-## Find plugins directory
-#if [ -n "${CLARA_PLUGINS}" ]; then
-#    if [ ! -d "${CLARA_PLUGINS}" ]; then
-#        echo "Error: \$CLARA_PLUGINS is not a directory."
-#        exit 1
-#    fi
-#    plugins_dir="${CLARA_PLUGINS}"
-#else
-#    plugins_dir="${CLARA_HOME}/plugins"
-#fi
-#
-#if [ -z "${CLASSPATH}" ]; then
-#    CLASSPATH="${CLARA_HOME}/lib/*"
-#
-#    # Add every plugin
-#    for plugin in "${plugins_dir}"/*; do
-#        if [ -d "${plugin}" ]; then
-#            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
-#
-#            # Support subdirectories inside lib/
-#            for libdir in "${plugin}"/lib/*; do
-#                if [ -d "${libdir}" ]; then
-#                    CLASSPATH+=":${libdir}/*"
-#                fi
-#            done
-#        fi
-#    done
-#
-#    CLASSPATH+=":${CLARA_HOME}/services/*"
-#    export CLASSPATH
-#fi
+            # Support subdirectories inside lib/
+            for libdir in "${plugin}"/lib/*; do
+                if [ -d "${libdir}" ]; then
+                    CLASSPATH+=":${libdir}/*"
+                fi
+            done
+        fi
+      done
+    else
+      # Default is clas12 plugin
+        plugins_dir="${CLARA_HOME}/plugins/clas12"
+        CLASSPATH+=":${plugins_dir}/lib/clas/*:${plugins_dir}/lib/services/*"
+    fi
+    export CLASSPATH
+fi
 
 # set java.library.path
 #java_lib_path=
