j_dpe: set proper classpath
- If the user defines its own $CLASSPATH, use that instead of generating
  the classpath.
- If the user defines $CLARA_PLUGINS, use it as the plugins directory,
  otherwise use the default $CLARA_HOME/plugins.
- For each plugin in the plugins directory, append lib and services to
  the classpath.
- Support CLARA_HOME/services to not break old scripts.

diff --git a/scripts/unix/j_dpe b/scripts/unix/j_dpe
--- a/scripts/unix/j_dpe
+++ b/scripts/unix/j_dpe
@@ -7,6 +7,24 @@ if [ -z "${CLARA_HOME}" ]; then
     exit 1
 fi
 
-export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/*:$CLAS12DIR/services/*"
+if [ -z "${CLASSPATH}" ]; then
+    CLASSPATH="${CLARA_HOME}/lib/*"
+    if [ -n "${CLARA_PLUGINS}" ]; then
+        if [ ! -d "${CLARA_PLUGINS}" ]; then
+            echo "Error: \$CLARA_PLUGINS is not a directory."
+            exit 1
+        fi
+        plugins_dir="${CLARA_PLUGINS}"
+    else
+        plugins_dir="${CLARA_HOME}/plugins"
+    fi
+    for plugin in "${plugins_dir}"/*; do
+        if [ -d "${plugin}" ]; then
+            CLASSPATH+=":${plugin}/lib/*:${plugin}/services/*"
+        fi
+    done
+    CLASSPATH+=":${CLARA_HOME}/services/*"
+    export CLASSPATH
+fi
 
 $JAVA_HOME/bin/java -Xms1024m -Xmx2048m -XX:+UseNUMA -XX:+UseBiasedLocking org.jlab.clara.sys.Dpe "$@"
